version: "3"

services:
  db:
    container_name: Vehicle-Tracker-MongoDB
    image: mongo:latest
    restart: always
    volumes:
      - ./mongodb:/data/db
  api:
    build: ./vehicle_tracker_api
    command: npm start bootstrap
    container_name: Vehicle-Tracker-API
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: vehicle-tracker:api
    restart: always
  webui:
    build: ./vehicle_tracker_webui
    container_name: Vehicle-Tracker-WEBUI
    depends_on:
      - db
    extra_hosts:
    image: vehicle-tracker:webui
    restart: always
    volumes:
      - ./vehicle_tracker_webui/dist:/app/dist
  nginx:
    container_name: Vehicle-Tracker-NGINX
    depends_on:
      - api
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/ssl/certs
      - ./vehicle_tracker_webui/dist:/var/www/html
